import {
  Incident,
  ActiveAlert,
  OperationRecord,
  ResourceUnit,
  AllocationAdvisory,
  AerialAsset,
  PlatformReport,
} from '../types'

export const FALLBACK_INCIDENTS: Incident[] = [
  {
    id: 'inc-a',
    title: 'Cyclone Alpha 4 — Central Grid Failure & Coastal Basin Surge',
    category: 'Cyclone',
    type: 'cyclone',
    location: 'Sector 7G / Coastal Basin',
    sector: 'Sector 7G',
    impact: 'Severe surge • 15 civilians isolated in pocket • Route 9 Bridge damaged',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    timeReported: '10:42 AM',
    lastUpdated: '12s ago',
    affectedPopulationEst: '2.4M',
    affectedAreaSqKm: 1420,
    priorityLevel: 'Level 1',
    resourceCoverage: '84%',
    isFieldVerified: false,
    sourceCounts: {
      citizenReports: 18,
      newsReports: 3,
      governmentReports: 1,
      weatherReports: 1,
      fieldAssessments: 0,
    },
    associatedOperations: ['Sector 7G Flood Extraction', 'Causeway Bridge Ground Evacuation'],
    reports: [
      {
        id: 'rep-101',
        sourceType: 'WEATHER',
        sourceLabel: 'IMD Early Warning Radar',
        timestamp: '10:15 AM',
        channelBadge: 'IMD_METEO',
        confidence: 96,
        summary: 'Cyclone Alpha 4 landfall confirmed. Sustained winds 120km/h with heavy coastal surge (>140mm/hr).',
        rawContent: 'RADAR_LOC: 29.76N/95.36W | WIND_MAX: 124km/h | SURGE_EST: 2.8m | THREAT: HIGH',
      },
      {
        id: 'rep-102',
        sourceType: 'CITIZEN',
        sourceLabel: 'Citizen SMS Broadcast Gateway',
        timestamp: '10:28 AM',
        channelBadge: 'CELL_SMS',
        confidence: 90,
        summary: 'Water rising rapidly near Sector 7G school. 15 people trapped on building rooftop. Need immediate rescue!',
        rawContent: 'SMS_ID: 98124 | SENDER: +919876543210 | MSG: Water 6ft deep at Sector 7 school rooftop. 15 trapped.',
      },
      {
        id: 'rep-103',
        sourceType: 'CITIZEN',
        sourceLabel: 'Citizen IVR Emergency Voice Ingestion',
        timestamp: '10:35 AM',
        channelBadge: 'IVR_VOICE',
        confidence: 88,
        summary: 'Caller reports Route 9 causeway bridge underpass completely submerged. Debris blocking road exit.',
        rawContent: 'CALL_SID: CA8891 | EXTRACTED: Location=Route 9 Bridge; Hazard=Submerged road; Urgency=Critical',
      },
      {
        id: 'rep-104',
        sourceType: 'NEWS',
        sourceLabel: 'National Broadcast Network',
        timestamp: '10:40 AM',
        channelBadge: 'MEDIA_INTEL',
        confidence: 94,
        summary: 'Breaking: Coastal substation tripping causes blackout across Sector 7G metro. Hospital C switched to emergency backup.',
      },
      {
        id: 'rep-105',
        sourceType: 'GOVERNMENT',
        sourceLabel: 'State Disaster Management Authority (SDMA)',
        timestamp: '10:42 AM',
        channelBadge: 'GOV_BULLETIN',
        confidence: 99,
        summary: 'Mandatory evacuation order active for Coastal Basin. Deploying swift-water response units.',
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        timestamp: '10:15 AM',
        title: 'Proactive Ingestion: IMD Cyclone Warning',
        description: 'Incident created from proactive meteorological radar feed before citizen reports arrived.',
        type: 'INGESTION',
      },
      {
        id: 'tl-2',
        timestamp: '10:30 AM',
        title: 'Multi-Channel Citizen Corroboration Ingested',
        description: '18 SMS and IVR voice reports corroborated to Incident inc-a without spawning duplicates.',
        type: 'INGESTION',
      },
      {
        id: 'tl-3',
        timestamp: '10:42 AM',
        title: 'Severity Escalated to CRITICAL',
        description: 'Power grid failure + rooftop trapping escalated incident priority to Level 1.',
        type: 'SEVERITY_UPDATE',
      },
    ],
  },
  {
    id: 'inc-b',
    title: 'Incident B — Highway 4 Flooding & Causeway Blockage',
    category: 'Flood',
    type: 'flood',
    location: 'Coastal Causeway Km 18',
    sector: 'Sector 4B',
    impact: 'Submerged underpass • 3 vehicles stranded • Water depth 4.2ft',
    severity: 'HIGH',
    status: 'ACTIVE',
    timeReported: '10:35 AM',
    lastUpdated: '1m ago',
    affectedPopulationEst: '450',
    affectedAreaSqKm: 120,
    priorityLevel: 'Level 2',
    resourceCoverage: '70%',
    isFieldVerified: false,
    sourceCounts: {
      citizenReports: 8,
      newsReports: 1,
      governmentReports: 1,
      weatherReports: 1,
      fieldAssessments: 0,
    },
    associatedOperations: ['Highway 4 Water Extraction'],
    reports: [
      {
        id: 'rep-201',
        sourceType: 'CITIZEN',
        sourceLabel: 'Citizen Web App Submission',
        timestamp: '10:35 AM',
        channelBadge: 'WEB_APP',
        confidence: 89,
        summary: '3 passenger cars stranded in Causeway underpass. Water rising rapidly past door handles.',
      },
    ],
    timeline: [
      {
        id: 'tl-b1',
        timestamp: '10:35 AM',
        title: 'Highway 4 Submersion Reported',
        description: 'Citizen web report received and verified via highway traffic camera feed.',
        type: 'INGESTION',
      },
    ],
  },
  {
    id: 'inc-c',
    title: 'Incident C — Comms Tower Delta Offline',
    category: 'Building damage',
    type: 'infrastructure',
    location: 'Highland Ridge Sector 1',
    sector: 'Sector 1',
    impact: 'Cell coverage degraded 30% • Radio fallback active',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    timeReported: '10:15 AM',
    lastUpdated: '4m ago',
    affectedPopulationEst: '12,000',
    affectedAreaSqKm: 340,
    priorityLevel: 'Level 3',
    resourceCoverage: '90%',
    isFieldVerified: false,
    sourceCounts: {
      citizenReports: 4,
      newsReports: 0,
      governmentReports: 1,
      weatherReports: 0,
      fieldAssessments: 0,
    },
    associatedOperations: ['Telecom Backup Link'],
    reports: [
      {
        id: 'rep-301',
        sourceType: 'GOVERNMENT',
        sourceLabel: 'Telecom Authority Telemetry',
        timestamp: '10:15 AM',
        channelBadge: 'TELECOM',
        confidence: 98,
        summary: 'Primary repeater lost grid power; backup generator running on 2h battery bank.',
      },
    ],
    timeline: [
      {
        id: 'tl-c1',
        timestamp: '10:15 AM',
        title: 'Comms Outage Detected',
        description: 'Automated network monitoring ping detected Tower Delta switch-over.',
        type: 'INGESTION',
      },
    ],
  },
  {
    id: 'inc-d',
    title: 'Incident D — East Levee Seepage Warning',
    category: 'Flood',
    type: 'flood',
    location: 'Riverfront Sector 2',
    sector: 'Sector 2',
    impact: 'Pre-breach seepage • 400 households alerted',
    severity: 'HIGH',
    status: 'MONITORING',
    timeReported: '09:58 AM',
    lastUpdated: '10m ago',
    affectedPopulationEst: '1,600',
    affectedAreaSqKm: 85,
    priorityLevel: 'Level 2',
    resourceCoverage: '75%',
    isFieldVerified: false,
    sourceCounts: {
      citizenReports: 3,
      newsReports: 1,
      governmentReports: 2,
      weatherReports: 1,
      fieldAssessments: 0,
    },
    associatedOperations: ['East Levee Sandbagging'],
    reports: [
      {
        id: 'rep-401',
        sourceType: 'GOVERNMENT',
        sourceLabel: 'Irrigation & Flood Control Board',
        timestamp: '09:58 AM',
        channelBadge: 'FLOOD_CONTROL',
        confidence: 95,
        summary: 'Water level at 94% retention capacity. Micro-seepage observed along eastern embankment.',
      },
    ],
    timeline: [
      {
        id: 'tl-d1',
        timestamp: '09:58 AM',
        title: 'Levee Watch Initiated',
        description: 'Engineering patrol flagged seepage for priority monitoring.',
        type: 'INGESTION',
      },
    ],
  },
]

export const FALLBACK_ALERTS: ActiveAlert[] = [
  {
    id: 'alt-1',
    time: '10:42 AM',
    category: 'INFRASTRUCTURE',
    source: 'Power Grid SCADA Gateway',
    location: 'Sector 7G Metro Substation',
    message: 'Hospital C power issue detected. Backup generators engaged but showing low fuel reserves (4h remaining).',
    severity: 'critical',
    relatedIncidentId: 'inc-a',
    relatedIncidentTitle: 'Cyclone Alpha 4 (Sector 7G)',
    isReviewedByAuthority: false,
  },
  {
    id: 'alt-2',
    time: '10:28 AM',
    category: 'CIVIL',
    source: 'Civil Protection Broadcast',
    location: 'Lowland Coastal Sector 7',
    message: 'Evacuation warning issued for Lowland Sector 7G. Traffic congestion reported on exit routes.',
    severity: 'warning',
    relatedIncidentId: 'inc-a',
    relatedIncidentTitle: 'Cyclone Alpha 4 (Sector 7G)',
    isReviewedByAuthority: true,
  },
  {
    id: 'alt-3',
    time: '10:15 AM',
    category: 'METEO',
    source: 'IMD Cyclone Doppler Feed',
    location: 'Coastal Basin Grid',
    message: 'Weather update: Sustained winds decreasing, but precipitation expected to increase by 20mm/hr over coastal basin.',
    severity: 'info',
    relatedIncidentId: 'inc-a',
    relatedIncidentTitle: 'Cyclone Alpha 4 (Sector 7G)',
    isReviewedByAuthority: true,
  },
  {
    id: 'alt-4',
    time: '09:55 AM',
    category: 'MEDICAL',
    source: 'EMS Regional Dispatch',
    location: 'Station 7 Clinic',
    message: 'Urgent medical supplies requested at Station 7: 50x trauma kits, insulin refrigeration units.',
    severity: 'warning',
    isReviewedByAuthority: false,
  },
]

export const FALLBACK_OPERATIONS: OperationRecord[] = [
  {
    id: 'OP-8821',
    operationType: 'Rescue Team Mission',
    incidentId: 'inc-a',
    incidentTitle: 'Cyclone Alpha 4 (Sector 7G)',
    resourceId: 'res-rec-1',
    resourceName: 'NDRF Swift Rescue Squad 4',
    location: 'Sector 7G School Rooftop',
    state: 'IN OPERATION',
    dispatchedTime: '10:32 AM',
    estimatedCompletion: '11:15 AM',
    authorizedBy: 'Cmdr. J. Vance',
    missionObjective: 'Extract 15 trapped civilians from school rooftop using motorized rafts and portable winches.',
    fieldUpdates: [
      '10:32 AM: Squad deployed from Base Alpha.',
      '10:45 AM: Reached Sector 7G perimeter; water depth 4.5ft.',
      '10:52 AM: Contact established with rooftop occupants. Commencing extraction.',
    ],
  },
  {
    id: 'OP-8822',
    operationType: 'Heavy Route Clearance',
    incidentId: 'inc-b',
    incidentTitle: 'Incident B (Highway 4)',
    resourceId: 'res-lan-1',
    resourceName: 'Heavy Dozer Unit Alpha',
    location: 'Coastal Causeway Km 18',
    state: 'IN TRANSIT',
    dispatchedTime: '10:40 AM',
    estimatedCompletion: '11:45 AM',
    authorizedBy: 'Cmdr. J. Vance',
    missionObjective: 'Clear debris and sub-surface rock obstruction from underpass road bed to allow ambulance passage.',
    fieldUpdates: [
      '10:40 AM: Dispatched via inland detour route.',
      '10:50 AM: ETA on scene 25 minutes.',
    ],
  },
]

export const FALLBACK_RESOURCES: ResourceUnit[] = [
  {
    id: 'res-med-1',
    name: 'Mobile Trauma Care Unit 1',
    category: 'medical',
    status: 'AVAILABLE',
    location: 'Sector 7G / Coastal Basin',
    personnelCount: 8,
    equipmentDetails: '3 Ambulances • 2 Emergency Physicians • 6 Trauma Backpacks',
  },
  {
    id: 'res-med-2',
    name: 'Field Surgical Hospital Team',
    category: 'medical',
    status: 'IN OPERATION',
    location: 'Sector 7G / Coastal Basin',
    personnelCount: 14,
    equipmentDetails: 'Triage Tent • 4 ICU Beds • Generator Backup',
  },
  {
    id: 'res-sec-1',
    name: 'Rapid Security Patrol Bravo',
    category: 'police_army',
    status: 'AVAILABLE',
    location: 'Coastal Causeway Km 18',
    personnelCount: 20,
    equipmentDetails: '4 All-Terrain Jeeps • Perimeter Lighting • Radio Mesh',
  },
  {
    id: 'res-rec-1',
    name: 'NDRF Swift Rescue Squad 4',
    category: 'rescue',
    status: 'IN OPERATION',
    location: 'Sector 7G / Coastal Basin',
    personnelCount: 12,
    equipmentDetails: '4 Inflatable Motorboats • Life Jackets • High-Wire Harnesses',
  },
  {
    id: 'res-air-1',
    name: 'Drone Alpha (Recon Spec)',
    category: 'aerial',
    status: 'AVAILABLE',
    location: 'Sector 7G / Coastal Basin',
    personnelCount: 2,
    equipmentDetails: 'Thermal FLIR Camera • 4K Optical 30x • 45min Flight Time',
  },
  {
    id: 'res-air-2',
    name: 'Air Evacuation Chopper 1',
    category: 'aerial',
    status: 'AVAILABLE',
    location: 'Regional Airbase',
    personnelCount: 4,
    equipmentDetails: 'Heavy Hoist • 6 Stretcher Capacity • Dual-Turbine',
  },
  {
    id: 'res-wat-1',
    name: 'Swift Water Rescue Boat 2',
    category: 'water',
    status: 'AVAILABLE',
    location: 'Riverfront Sector 2',
    personnelCount: 6,
    equipmentDetails: 'Rigid Inflatable Hull • 150HP Outboard • Flood Searchlights',
  },
  {
    id: 'res-lan-1',
    name: 'Heavy Engineering Dozer B',
    category: 'land',
    status: 'AVAILABLE',
    location: 'Coastal Causeway Km 18',
    personnelCount: 3,
    equipmentDetails: 'Hydraulic Blade • Winch Cable 20-ton • Armored Cab',
  },
  {
    id: 'res-shl-1',
    name: 'Sector 7 Community Shelter',
    category: 'shelter',
    status: 'AVAILABLE',
    location: 'Sector 7G / Coastal Basin',
    personnelCount: 10,
    equipmentDetails: 'Emergency Bedding • Sanitation Units • Diesel Generator',
    shelterCapacity: 1500,
    shelterOccupied: 1120,
  },
  {
    id: 'res-sup-1',
    name: 'Central Food & Medical Depot',
    category: 'supplies',
    status: 'AVAILABLE',
    location: 'Civic Arena Shelter District',
    personnelCount: 6,
    equipmentDetails: 'Ready-to-eat rations, bulk bottled water, sterile dressings',
    suppliesFoodDays: 7,
    suppliesFoodPeople: 5000,
    suppliesMedicineCount: 450,
    suppliesClothingCount: 1200,
  },
]

export const FALLBACK_ADVISORIES: AllocationAdvisory[] = [
  {
    id: 'adv-1',
    targetIncidentId: 'inc-a',
    resourceName: 'Medical Team Alpha',
    resourceCategory: 'medical',
    targetIncident: 'Incident A (Sector 7G)',
    details: '12 personnel • 3 vehicles • ~18 km',
    reason: 'Medical emergency triage required for 15 isolated civilians reported on rooftop.',
    status: 'RECOMMENDED',
    metrics: {
      capabilityMatch: 100,
      proximity: 92,
      travelTime: '18 min',
      scarcity: 'HIGH',
      competingIncidents: 2,
    },
  },
  {
    id: 'adv-2',
    targetIncidentId: 'inc-b',
    resourceName: 'Swift Water Boat Unit 3',
    resourceCategory: 'boat',
    targetIncident: 'Incident B (Highway 4)',
    details: '2 boats • 8 personnel • ~24 km',
    reason: 'Highway underpass flooding with stranded vehicles requires water extraction capability.',
    status: 'RECOMMENDED',
    metrics: {
      capabilityMatch: 95,
      proximity: 88,
      travelTime: '24 min',
      scarcity: 'MEDIUM',
      competingIncidents: 1,
    },
  },
]

export const FALLBACK_AERIAL_ASSETS: AerialAsset[] = [
  { id: 'drone-1', name: 'Drone Alpha', type: 'drone', status: 'AVAILABLE' },
  { id: 'helo-2', name: 'Helicopter 02', type: 'helicopter', status: 'AVAILABLE' },
  { id: 'helo-3', name: 'Rescue Helicopter', type: 'helicopter', status: 'IN USE' },
]

export const FALLBACK_REPORTS: PlatformReport[] = [
  {
    id: 'REP-901',
    reportType: 'Incident Debrief',
    title: 'Cyclone Alpha 4 Phase 1 Ingestion & Surge Analysis',
    timestamp: '10:45 AM',
    relatedIncidentId: 'inc-a',
    author: 'Chief Situational Analyst',
    summary: 'Unified multi-source intelligence ingestion confirmed high-risk surge pattern across Sector 7G Coastal Basin. Deduplication engine successfully prevented multiple duplicate incidents from 18 citizen calls.',
    metricsSummary: '2.4M Exposed • Level 1 Priority • 84% Resource Cov.',
    tags: ['cyclone', 'surge', 'deduplication', 'sector7g'],
  },
  {
    id: 'REP-902',
    reportType: 'Assessment Mission Report',
    title: 'Field Recon Mission SCAN-44A Post-Flight Telemetry',
    timestamp: '10:30 AM',
    relatedIncidentId: 'inc-a',
    author: 'Drone Operator Alpha (Sector 7G)',
    summary: 'Visual sensor payload verified impassable status of Route 9 causeway bridge underpass. Approximately 15 civilians isolated on school building upper floor.',
    metricsSummary: 'Confidence: 91% • 2 Structures Damaged',
    tags: ['aerial_recon', 'flir', 'route9_block'],
  },
  {
    id: 'REP-903',
    reportType: 'Authority Decision Log',
    title: 'Emergency Resource Rebalancing Directive #44',
    timestamp: '10:15 AM',
    author: 'Cmdr. J. Vance (Level 5)',
    summary: 'Authority signed off allocation of swift-water motorized rafts and heavy engineering dozers to establish emergency extraction corridors.',
    metricsSummary: '2 Units Dispatched • 0 Auto-Dispatches',
    tags: ['authority_decision', 'allocation', 'ndrf'],
  },
]
