"""create_initial_core_schema

Revision ID: 41ecd5015911
Revises: 
Create Date: 2026-08-22 15:40:37.864691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ecd5015911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disaster_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('affected_population', sa.String(length=50), nullable=True),
    sa.Column('affected_area_sq_km', sa.Float(), nullable=True),
    sa.Column('resource_coverage_pct', sa.Integer(), nullable=True),
    sa.Column('is_field_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_disaster_type'), 'incidents', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_name'), 'inventory', ['item_name'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('base_location', sa.String(length=255), nullable=False),
    sa.Column('personnel_count', sa.Integer(), nullable=True),
    sa.Column('equipment_details', sa.Text(), nullable=True),
    sa.Column('shelter_capacity', sa.Integer(), nullable=True),
    sa.Column('shelter_occupied', sa.Integer(), nullable=True),
    sa.Column('supplies_food_days', sa.Integer(), nullable=True),
    sa.Column('supplies_food_people', sa.Integer(), nullable=True),
    sa.Column('supplies_medicine_count', sa.Integer(), nullable=True),
    sa.Column('supplies_clothing_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_base_location'), 'resources', ['base_location'], unique=False)
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_table('shelters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_name'), 'shelters', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_reviewed_by_authority', sa.Boolean(), nullable=True),
    sa.Column('alert_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_mode', sa.String(length=50), nullable=False),
    sa.Column('mission_type', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('assessment_time', sa.String(length=50), nullable=True),
    sa.Column('weather_conditions', sa.String(length=255), nullable=True),
    sa.Column('area_surveyed', sa.String(length=255), nullable=False),
    sa.Column('hazards_detected', sa.Text(), nullable=True),
    sa.Column('structures_damaged_count', sa.Integer(), nullable=True),
    sa.Column('road_accessibility_status', sa.String(length=100), nullable=False),
    sa.Column('people_observed', sa.String(length=255), nullable=True),
    sa.Column('recommended_resources', sa.Text(), nullable=True),
    sa.Column('evacuation_route_status', sa.String(length=100), nullable=True),
    sa.Column('operator_observations', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('media_file_urls', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_incident_id'), 'assessments', ['incident_id'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('disaster_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_people_trapped', sa.Boolean(), nullable=True),
    sa.Column('is_immediate_danger', sa.Boolean(), nullable=True),
    sa.Column('affected_people_estimate', sa.String(length=50), nullable=True),
    sa.Column('citizen_contact', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_reports_incident_id'), 'citizen_reports', ['incident_id'], unique=False)
    op.create_table('incident_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('channel_badge', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_sources_incident_id'), 'incident_sources', ['incident_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('destination_location', sa.String(length=255), nullable=False),
    sa.Column('authorized_by', sa.String(length=255), nullable=False),
    sa.Column('mission_objective', sa.Text(), nullable=False),
    sa.Column('dispatched_time', sa.String(length=50), nullable=False),
    sa.Column('estimated_completion', sa.String(length=50), nullable=True),
    sa.Column('field_updates_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_incident_id'), 'operations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_operations_resource_id'), 'operations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_operations_state'), 'operations', ['state'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics_summary', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_incident_id'), 'reports', ['incident_id'], unique=False)
    op.create_table('resource_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('travel_time_est', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_allocations_incident_id'), 'resource_allocations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_resource_id'), 'resource_allocations', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_allocations_resource_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_incident_id'), table_name='resource_allocations')
    op.drop_table('resource_allocations')
    op.drop_index(op.f('ix_reports_incident_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_operations_state'), table_name='operations')
    op.drop_index(op.f('ix_operations_resource_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_incident_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_incident_sources_incident_id'), table_name='incident_sources')
    op.drop_table('incident_sources')
    op.drop_index(op.f('ix_citizen_reports_incident_id'), table_name='citizen_reports')
    op.drop_table('citizen_reports')
    op.drop_index(op.f('ix_assessments_incident_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shelters_name'), table_name='shelters')
    op.drop_table('shelters')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_index(op.f('ix_resources_base_location'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_inventory_item_name'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_disaster_type'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
